rules = [
    ('S', ['program']),
    ('program', ['expression']),
    ('expression', ['assignment']),
    ('expression', ['logical_expr']),
    ('assignment', ['ID', 'ASSIGN', 'expression']),
    ('logical_expr', ['logical_expr', 'OR', 'logical_term']),
    ('logical_expr', ['logical_term']),
    ('logical_term', ['logical_term', 'AND', 'logical_factor']),
    ('logical_term', ['logical_factor']),
    ('logical_factor', ['NOT', 'logical_factor']),
    ('logical_factor', ['relational_expr']),
    ('relational_expr', ['relational_expr', 'EQ', 'additive_expr']),
    ('relational_expr', ['relational_expr', 'NEQ', 'additive_expr']),
    ('relational_expr', ['relational_expr', 'LT', 'additive_expr']),
    ('relational_expr', ['relational_expr', 'LE', 'additive_expr']),
    ('relational_expr', ['relational_expr', 'GT', 'additive_expr']),
    ('relational_expr', ['relational_expr', 'GE', 'additive_expr']),
    ('relational_expr', ['additive_expr']),
    ('additive_expr', ['additive_expr', 'PLUS', 'multiplicative_expr']),
    ('additive_expr', ['additive_expr', 'MINUS', 'multiplicative_expr']),
    ('additive_expr', ['multiplicative_expr']),
    ('multiplicative_expr', ['multiplicative_expr', 'MUL', 'unary_expr']),
    ('multiplicative_expr', ['multiplicative_expr', 'DIV', 'unary_expr']),
    ('multiplicative_expr', ['unary_expr']),
    ('unary_expr', ['MINUS', 'unary_expr']),
    ('unary_expr', ['primary_expr']),
    ('primary_expr', ['LPAREN', 'expression', 'RPAREN']),
    ('primary_expr', ['ID']),
    ('primary_expr', ['NUMBER']),
    ('primary_expr', ['TRUE']),
    ('primary_expr', ['FALSE']),
    ('primary_expr', ['function_definition']),
    ('primary_expr', ['function_call']),
    ('function_definition', ['ID', 'LPAREN', 'argument_list', 'RPAREN', 'LBRACE', 'expression', 'RBRACE']),
    ('function_call', ['ID', 'LPAREN', 'argument_list', 'RPAREN']),
    ('argument_list', ['argument_list', 'COMMA', 'expression']),
    ('argument_list', ['expression']),
]

action_table = {
    0: {
        "ID": 5,
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    1: {"$end": 0},
    2: {"$end": -1},
    3: {"$end": -2, "RPAREN": -2, "COMMA": -2, "RBRACE": -2},
    4: {"$end": -3, "RPAREN": -3, "COMMA": -3, "RBRACE": -3, "OR": 21},
    5: {
        "ASSIGN": 22,
        "MUL": -27,
        "DIV": -27,
        "PLUS": -27,
        "MINUS": -27,
        "EQ": -27,
        "NEQ": -27,
        "LT": -27,
        "LE": -27,
        "GT": -27,
        "GE": -27,
        "AND": -27,
        "OR": -27,
        "$end": -27,
        "RPAREN": -27,
        "COMMA": -27,
        "RBRACE": -27,
        "LPAREN": 23,
    },
    6: {"OR": -6, "$end": -6, "RPAREN": -6, "COMMA": -6, "RBRACE": -6, "AND": 24},
    7: {"AND": -8, "OR": -8, "$end": -8, "RPAREN": -8, "COMMA": -8, "RBRACE": -8},
    8: {
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "ID": 26,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    9: {
        "AND": -10,
        "OR": -10,
        "$end": -10,
        "RPAREN": -10,
        "COMMA": -10,
        "RBRACE": -10,
        "EQ": 27,
        "NEQ": 28,
        "LT": 29,
        "LE": 30,
        "GT": 31,
        "GE": 32,
    },
    10: {
        "EQ": -17,
        "NEQ": -17,
        "LT": -17,
        "LE": -17,
        "GT": -17,
        "GE": -17,
        "AND": -17,
        "OR": -17,
        "$end": -17,
        "RPAREN": -17,
        "COMMA": -17,
        "RBRACE": -17,
        "PLUS": 33,
        "MINUS": 34,
    },
    11: {
        "PLUS": -20,
        "MINUS": -20,
        "EQ": -20,
        "NEQ": -20,
        "LT": -20,
        "LE": -20,
        "GT": -20,
        "GE": -20,
        "AND": -20,
        "OR": -20,
        "$end": -20,
        "RPAREN": -20,
        "COMMA": -20,
        "RBRACE": -20,
        "MUL": 35,
        "DIV": 36,
    },
    12: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    13: {
        "MUL": -23,
        "DIV": -23,
        "PLUS": -23,
        "MINUS": -23,
        "EQ": -23,
        "NEQ": -23,
        "LT": -23,
        "LE": -23,
        "GT": -23,
        "GE": -23,
        "AND": -23,
        "OR": -23,
        "$end": -23,
        "RPAREN": -23,
        "COMMA": -23,
        "RBRACE": -23,
    },
    14: {
        "MUL": -25,
        "DIV": -25,
        "PLUS": -25,
        "MINUS": -25,
        "EQ": -25,
        "NEQ": -25,
        "LT": -25,
        "LE": -25,
        "GT": -25,
        "GE": -25,
        "AND": -25,
        "OR": -25,
        "$end": -25,
        "RPAREN": -25,
        "COMMA": -25,
        "RBRACE": -25,
    },
    15: {
        "ID": 5,
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    16: {
        "MUL": -28,
        "DIV": -28,
        "PLUS": -28,
        "MINUS": -28,
        "EQ": -28,
        "NEQ": -28,
        "LT": -28,
        "LE": -28,
        "GT": -28,
        "GE": -28,
        "AND": -28,
        "OR": -28,
        "$end": -28,
        "RPAREN": -28,
        "COMMA": -28,
        "RBRACE": -28,
    },
    17: {
        "MUL": -29,
        "DIV": -29,
        "PLUS": -29,
        "MINUS": -29,
        "EQ": -29,
        "NEQ": -29,
        "LT": -29,
        "LE": -29,
        "GT": -29,
        "GE": -29,
        "AND": -29,
        "OR": -29,
        "$end": -29,
        "RPAREN": -29,
        "COMMA": -29,
        "RBRACE": -29,
    },
    18: {
        "MUL": -30,
        "DIV": -30,
        "PLUS": -30,
        "MINUS": -30,
        "EQ": -30,
        "NEQ": -30,
        "LT": -30,
        "LE": -30,
        "GT": -30,
        "GE": -30,
        "AND": -30,
        "OR": -30,
        "$end": -30,
        "RPAREN": -30,
        "COMMA": -30,
        "RBRACE": -30,
    },
    19: {
        "MUL": -31,
        "DIV": -31,
        "PLUS": -31,
        "MINUS": -31,
        "EQ": -31,
        "NEQ": -31,
        "LT": -31,
        "LE": -31,
        "GT": -31,
        "GE": -31,
        "AND": -31,
        "OR": -31,
        "$end": -31,
        "RPAREN": -31,
        "COMMA": -31,
        "RBRACE": -31,
    },
    20: {
        "MUL": -32,
        "DIV": -32,
        "PLUS": -32,
        "MINUS": -32,
        "EQ": -32,
        "NEQ": -32,
        "LT": -32,
        "LE": -32,
        "GT": -32,
        "GE": -32,
        "AND": -32,
        "OR": -32,
        "$end": -32,
        "RPAREN": -32,
        "COMMA": -32,
        "RBRACE": -32,
    },
    21: {
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "ID": 26,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    22: {
        "ID": 5,
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    23: {
        "ID": 5,
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    24: {
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "ID": 26,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    25: {"AND": -9, "OR": -9, "$end": -9, "RPAREN": -9, "COMMA": -9, "RBRACE": -9},
    26: {
        "MUL": -27,
        "DIV": -27,
        "PLUS": -27,
        "MINUS": -27,
        "EQ": -27,
        "NEQ": -27,
        "LT": -27,
        "LE": -27,
        "GT": -27,
        "GE": -27,
        "AND": -27,
        "OR": -27,
        "$end": -27,
        "RPAREN": -27,
        "COMMA": -27,
        "RBRACE": -27,
        "LPAREN": 23,
    },
    27: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    28: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    29: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    30: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    31: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    32: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    33: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    34: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    35: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    36: {"MINUS": 12, "LPAREN": 15, "ID": 26, "NUMBER": 16, "TRUE": 17, "FALSE": 18},
    37: {
        "MUL": -24,
        "DIV": -24,
        "PLUS": -24,
        "MINUS": -24,
        "EQ": -24,
        "NEQ": -24,
        "LT": -24,
        "LE": -24,
        "GT": -24,
        "GE": -24,
        "AND": -24,
        "OR": -24,
        "$end": -24,
        "RPAREN": -24,
        "COMMA": -24,
        "RBRACE": -24,
    },
    38: {"RPAREN": 54},
    39: {"OR": -5, "$end": -5, "RPAREN": -5, "COMMA": -5, "RBRACE": -5, "AND": 24},
    40: {"$end": -4, "RPAREN": -4, "COMMA": -4, "RBRACE": -4},
    41: {"RPAREN": 55, "COMMA": 56},
    42: {"RPAREN": -36, "COMMA": -36},
    43: {"AND": -7, "OR": -7, "$end": -7, "RPAREN": -7, "COMMA": -7, "RBRACE": -7},
    44: {
        "EQ": -11,
        "NEQ": -11,
        "LT": -11,
        "LE": -11,
        "GT": -11,
        "GE": -11,
        "AND": -11,
        "OR": -11,
        "$end": -11,
        "RPAREN": -11,
        "COMMA": -11,
        "RBRACE": -11,
        "PLUS": 33,
        "MINUS": 34,
    },
    45: {
        "EQ": -12,
        "NEQ": -12,
        "LT": -12,
        "LE": -12,
        "GT": -12,
        "GE": -12,
        "AND": -12,
        "OR": -12,
        "$end": -12,
        "RPAREN": -12,
        "COMMA": -12,
        "RBRACE": -12,
        "PLUS": 33,
        "MINUS": 34,
    },
    46: {
        "EQ": -13,
        "NEQ": -13,
        "LT": -13,
        "LE": -13,
        "GT": -13,
        "GE": -13,
        "AND": -13,
        "OR": -13,
        "$end": -13,
        "RPAREN": -13,
        "COMMA": -13,
        "RBRACE": -13,
        "PLUS": 33,
        "MINUS": 34,
    },
    47: {
        "EQ": -14,
        "NEQ": -14,
        "LT": -14,
        "LE": -14,
        "GT": -14,
        "GE": -14,
        "AND": -14,
        "OR": -14,
        "$end": -14,
        "RPAREN": -14,
        "COMMA": -14,
        "RBRACE": -14,
        "PLUS": 33,
        "MINUS": 34,
    },
    48: {
        "EQ": -15,
        "NEQ": -15,
        "LT": -15,
        "LE": -15,
        "GT": -15,
        "GE": -15,
        "AND": -15,
        "OR": -15,
        "$end": -15,
        "RPAREN": -15,
        "COMMA": -15,
        "RBRACE": -15,
        "PLUS": 33,
        "MINUS": 34,
    },
    49: {
        "EQ": -16,
        "NEQ": -16,
        "LT": -16,
        "LE": -16,
        "GT": -16,
        "GE": -16,
        "AND": -16,
        "OR": -16,
        "$end": -16,
        "RPAREN": -16,
        "COMMA": -16,
        "RBRACE": -16,
        "PLUS": 33,
        "MINUS": 34,
    },
    50: {
        "PLUS": -18,
        "MINUS": -18,
        "EQ": -18,
        "NEQ": -18,
        "LT": -18,
        "LE": -18,
        "GT": -18,
        "GE": -18,
        "AND": -18,
        "OR": -18,
        "$end": -18,
        "RPAREN": -18,
        "COMMA": -18,
        "RBRACE": -18,
        "MUL": 35,
        "DIV": 36,
    },
    51: {
        "PLUS": -19,
        "MINUS": -19,
        "EQ": -19,
        "NEQ": -19,
        "LT": -19,
        "LE": -19,
        "GT": -19,
        "GE": -19,
        "AND": -19,
        "OR": -19,
        "$end": -19,
        "RPAREN": -19,
        "COMMA": -19,
        "RBRACE": -19,
        "MUL": 35,
        "DIV": 36,
    },
    52: {
        "MUL": -21,
        "DIV": -21,
        "PLUS": -21,
        "MINUS": -21,
        "EQ": -21,
        "NEQ": -21,
        "LT": -21,
        "LE": -21,
        "GT": -21,
        "GE": -21,
        "AND": -21,
        "OR": -21,
        "$end": -21,
        "RPAREN": -21,
        "COMMA": -21,
        "RBRACE": -21,
    },
    53: {
        "MUL": -22,
        "DIV": -22,
        "PLUS": -22,
        "MINUS": -22,
        "EQ": -22,
        "NEQ": -22,
        "LT": -22,
        "LE": -22,
        "GT": -22,
        "GE": -22,
        "AND": -22,
        "OR": -22,
        "$end": -22,
        "RPAREN": -22,
        "COMMA": -22,
        "RBRACE": -22,
    },
    54: {
        "MUL": -26,
        "DIV": -26,
        "PLUS": -26,
        "MINUS": -26,
        "EQ": -26,
        "NEQ": -26,
        "LT": -26,
        "LE": -26,
        "GT": -26,
        "GE": -26,
        "AND": -26,
        "OR": -26,
        "$end": -26,
        "RPAREN": -26,
        "COMMA": -26,
        "RBRACE": -26,
    },
    55: {
        "LBRACE": 57,
        "MUL": -34,
        "DIV": -34,
        "PLUS": -34,
        "MINUS": -34,
        "EQ": -34,
        "NEQ": -34,
        "LT": -34,
        "LE": -34,
        "GT": -34,
        "GE": -34,
        "AND": -34,
        "OR": -34,
        "$end": -34,
        "RPAREN": -34,
        "COMMA": -34,
        "RBRACE": -34,
    },
    56: {
        "ID": 5,
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    57: {
        "ID": 5,
        "NOT": 8,
        "MINUS": 12,
        "LPAREN": 15,
        "NUMBER": 16,
        "TRUE": 17,
        "FALSE": 18,
    },
    58: {"RPAREN": -35, "COMMA": -35},
    59: {"RBRACE": 60},
    60: {
        "MUL": -33,
        "DIV": -33,
        "PLUS": -33,
        "MINUS": -33,
        "EQ": -33,
        "NEQ": -33,
        "LT": -33,
        "LE": -33,
        "GT": -33,
        "GE": -33,
        "AND": -33,
        "OR": -33,
        "$end": -33,
        "RPAREN": -33,
        "COMMA": -33,
        "RBRACE": -33,
    },
}

goto_table = {
    0: {
        "program": 1,
        "expression": 2,
        "assignment": 3,
        "logical_expr": 4,
        "logical_term": 6,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    1: {},
    2: {},
    3: {},
    4: {},
    5: {},
    6: {},
    7: {},
    8: {
        "logical_factor": 25,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    9: {},
    10: {},
    11: {},
    12: {
        "unary_expr": 37,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    13: {},
    14: {},
    15: {
        "expression": 38,
        "assignment": 3,
        "logical_expr": 4,
        "logical_term": 6,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    16: {},
    17: {},
    18: {},
    19: {},
    20: {},
    21: {
        "logical_term": 39,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    22: {
        "expression": 40,
        "assignment": 3,
        "logical_expr": 4,
        "logical_term": 6,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    23: {
        "argument_list": 41,
        "expression": 42,
        "assignment": 3,
        "logical_expr": 4,
        "logical_term": 6,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    24: {
        "logical_factor": 43,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    25: {},
    26: {},
    27: {
        "additive_expr": 44,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    28: {
        "additive_expr": 45,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    29: {
        "additive_expr": 46,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    30: {
        "additive_expr": 47,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    31: {
        "additive_expr": 48,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    32: {
        "additive_expr": 49,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    33: {
        "multiplicative_expr": 50,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    34: {
        "multiplicative_expr": 51,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    35: {
        "unary_expr": 52,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    36: {
        "unary_expr": 53,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    37: {},
    38: {},
    39: {},
    40: {},
    41: {},
    42: {},
    43: {},
    44: {},
    45: {},
    46: {},
    47: {},
    48: {},
    49: {},
    50: {},
    51: {},
    52: {},
    53: {},
    54: {},
    55: {},
    56: {
        "expression": 58,
        "assignment": 3,
        "logical_expr": 4,
        "logical_term": 6,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    57: {
        "expression": 59,
        "assignment": 3,
        "logical_expr": 4,
        "logical_term": 6,
        "logical_factor": 7,
        "relational_expr": 9,
        "additive_expr": 10,
        "multiplicative_expr": 11,
        "unary_expr": 13,
        "primary_expr": 14,
        "function_definition": 19,
        "function_call": 20,
    },
    58: {},
    59: {},
    60: {},
}
